### ISSUE TITLE
Retaliation with malicious intent issues

### ISSUE THREAD

**Issue by lazuee** [Itz-Hyperz/Discord-Security-Bot#15]
[Sus #1](https://github.com/Itz-Hyperz/Discord-Security-Bot/blob/a3f48e09c4a66eb5e00dff8c77d2de478a6012ab/events/message.js#L11)

[Sus #2](https://github.com/Itz-Hyperz/Discord-Security-Bot/blob/a3f48e09c4a66eb5e00dff8c77d2de478a6012ab/events/message.js#L86)

[Sus #3](https://github.com/Itz-Hyperz/Discord-Security-Bot/blob/a3f48e09c4a66eb5e00dff8c77d2de478a6012ab/events/ready.js#L48)

[Sus #4](https://github.com/Itz-Hyperz/Discord-Security-Bot/blob/a3f48e09c4a66eb5e00dff8c77d2de478a6012ab/events/guildCreate.js#L3)

**Comment by Itz-Hyperz** [comment]
Shoot me an email, thanks 
me@hyperz.net

**Comment by Itz-Hyperz** [comment]
Feel free to direct this conversation to #12
